### ISSUE TITLE
Remove lazy loading from ConnexionzClient and GoogleTransitClient

### ISSUE THREAD

**Issue by RikkiGibson** [RikkiGibson/Corvallis-Bus-Server#14]
The lazy loaded/cached properties on these clients necessitate recycling the app pool before performing an init task with new data. The methods that generate the data are only called during the init task, and we should just make sure to not call them redundantly.

**Comment by RikkiGibson** [comment]
Fixed in 8c28d5d

**Comment by cartermp** [comment]
poopybutt
