### ISSUE TITLE
Add /stops/ endpoint To API

### ISSUE THREAD

**Issue by ZacharyKhan** [RikkiGibson/Corvallis-Bus-Server#16]
It would be really convenient to have the API include a `/stops/` endpoint to return latitude and longitude information for each `stopID` provided.

The new endpoint could respond with a similar json response to the `/favorites/` endpoint or the `static` endpoint, but include latitude/longitude info for the stop as well. Maybe `/favorites/` could also return lat/long info on `stopID`'s to avoid hitting the new endpoint on top of `/favorites/` if you did need the lat/long data.

<img width="468" alt="screen shot 2017-12-13 at 2 22 31 pm" src="https://user-images.githubusercontent.com/14354004/33965588-51f15c76-e011-11e7-8546-529f7bb91cab.png">

**Comment by RikkiGibson** [comment]
I think it would be reasonable for `/favorites/` to put lat and long on there. If this API did time properly I would probably have it provide a machine-readable representation of the arrival times as well.

**Comment by RikkiGibson** [comment]
Are you looking for an endpoint that basically gives you a subset of the `/static` data or do you want to receive the arrival times along with more fields from the static data in one network call?

**Comment by ZacharyKhan** [comment]
You could have `/favorites/` return a subset of the `/static` data that contains the lat & long so that developers can immediately consume the data without extra processing (they would otherwise be forced to use `/static` to store all stop location data and process against the static data every time they hit `\favorites`) 

For example, in the image I posted above you could simply add a key `stop_coordinate` and have it return an array of `[lat, long]` as Doubles?

**Comment by RikkiGibson** [comment]
I’d like to have `lat`, `lng` keys for consistency. They’re named to match the names used in the Google Maps JS API. If you open a PR which adds those values to each favorite stop, I can merge and publish it.

**Comment by ZacharyKhan** [comment]
@RikkiGibson I actually am not sure how to implement that as I don't code in C# :(

**Comment by RikkiGibson** [comment]
It would be easiest if you have a Windows environment you can work in.

Favorite stops are created in this method: https://github.com/RikkiGibson/Corvallis-Bus-Server/blob/47af94820e38c58fb57590253170cb7d20daf8ac/CorvallisBusCore/TransitManager.cs#L201

Should be able to just modify the FavoriteStop and FavoriteStopViewModel types and pass around the extra information you want. When you test it locally, I think you have to browse to `localhost/api/tasks/init` the first time you run it so that the static data gets populated.

**Comment by ZacharyKhan** [comment]
If this were for a project or work I definitely would dive into this and try to do it but I'm simply building this open source app to consume your API for fun over Christmas break while I have time to kill :) 

Anyone care to helpout? 
@jschneidereit @shawncrabtree @cartermp

**Comment by RikkiGibson** [comment]
:tada: Reopen if there any problems with this change :)
