### ISSUE TITLE
Add support for multi-route directions 

### ISSUE THREAD

**Issue by ZacharyKhan** [RikkiGibson/Corvallis-Bus-Server#22]
It would be super convenient to have an endpoint that **takes the users current location coordinate and the destination coordinate as input** and **returns JSON data that includes**:

 - **All bus routes the user will need to take to get to their destination**
 - **For each route the user will take on the trip, which stop should they get on and off**

I'm sure I may be missing something here and I am aware that this is not the easiest and quickest thing to implement, but I feel adding this capability to the API will take it to the next level, allowing developers to really build something robust.

**Comment by RikkiGibson** [comment]
Google Transit REST APIs might be able to get you some of the way here

**Comment by RikkiGibson** [comment]
Also I don't know if anyone anywhere has made use of the flow-through routes for trip planning https://www.corvallisoregon.gov/cts/page/routes

**Comment by RikkiGibson** [comment]
You're right that it could be really cool. Up to this point the API and apps have not made a strong attempt at a trip planning feature.
