### ISSUE TITLE
What the heck is going on?

### ISSUE THREAD

**Issue by asdjfhlksdjhfasdjf** [RikkiGibson/Corvallis-Bus-Server#24]
When I try to access the summary route, it displays random nonsense strings...

What is even weirder, it ONLY returns this nonsense when I call the API from within my iOS app. If I call the route from a browser or terminal it shows the correct data. 

This leads me to believe you are purposely checking for my app and feeding nonsense. If not, why is only my app showing this?

Also, I had to create a new GitHub just to create this issue. I assume you blocked my main account?

Not sure why you're doing this, please explain? I have an app on the App Store and all of my users are now not able to use the app because there is no real data!

<img width="907" alt="screen shot 2018-01-29 at 2 06 58 pm" src="https://user-images.githubusercontent.com/35939717/35538757-cfeb1ae2-0503-11e8-9523-a7eba7c74ce4.png">

**Comment by asdjfhlksdjhfasdjf** [comment]
If someone could help me out and get me some answers as to where this nonsense data is coming from, that would be really awesome. I have a live app on the App Store that is useless as of right now.

**Comment by asdjfhlksdjhfasdjf** [comment]
I see you have also given me a 1 star review on the App Store. This is really sad @RikkiGibson, I will be switching over to google transit, reporting you to the Corvallis Transit.

**Comment by cartermp** [comment]
<img width="323" alt="screen shot 2018-01-29 at 3 09 36 pm" src="https://user-images.githubusercontent.com/6309070/35539453-72f6ff10-0506-11e8-81a1-d082f738eeb1.png">

Implement your own server and stop being a dick.

**Comment by asdjfhlksdjhfasdjf** [comment]
LOOOOL

What a joke? I made this app for free, just because your app was that shitty and I was trying to make something better for users. 

So, I will scrape your server from before it was updated to F my stuff up and host that. Also, I will be visiting you and Rikki at the Redmond Campus soon enough. 

Asshole

**Comment by cartermp** [comment]
Have a lovely day. You'll go far
